### ISSUE TITLE
npm install results in 401 Unauthorized

### ISSUE THREAD

**Issue by rodgersgb** [swimlane/ngx-dnd#133]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Sorry, we will not be able to answer every support request.  Please consider other venues for support requests
```

**Current behavior**
$ npm install @swimlane/ngx-dnd
npm ERR! code E401
npm ERR! 401 Unauthorized: @swimlane/ngx-dnd@^4.0.2

**Expected behavior**
Authorized installation.

**Reproduction of the problem**
debug log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\grodgers\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@swimlane/ngx-dnd' ]
2 info using npm@6.0.0
3 info using node@v8.11.1
4 verbose npm-session 1137b286856a167b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 401 https://registry.npmjs.org/@swimlane%2fngx-dnd 128ms
8 silly fetchPackageMetaData error for @swimlane/ngx-dnd@^4.0.2 401 Unauthorized: @swimlane/ngx-dnd@^4.0.2
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 2047ms
11 verbose stack Error: 401 Unauthorized: @swimlane/ngx-dnd@^4.0.2
11 verbose stack     at fetch.then.res (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (C:\Users\grodgers\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:794:20)
11 verbose stack     at tryOnImmediate (timers.js:752:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
12 verbose cwd D:\projects\blademodules\ang5\git\blade
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\grodgers\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@swimlane/ngx-dnd"
15 verbose node v8.11.1
16 verbose npm  v6.0.0
17 error code E401
18 error 401 Unauthorized: @swimlane/ngx-dnd@^4.0.2
19 verbose exit [ 1, true ]

**Comment by rodgersgb** [comment]
I fixed this issue by fetching a new token from registry.npmjs.org. Not sure why @swimlane was rejecting the previous one. I was able to install other public packages with the older token.
